### ISSUE TITLE
TypedController render props object doesn't have a name prop

### ISSUE THREAD

**Issue by christopher-francisco** [react-hook-form/strictly-typed#15]
I'm currently defining the generic as `any` because I get an error [on this discussion](https://github.com/react-hook-form/react-hook-form/discussions/2615) and I'm not sure how to handle it.

```javascript
type FormData = any;

//...
  const TypedController = useTypedController<FormData>({ control });

//...

  <TypedController
    name="documentType"
    render={props => {
      debugger;   // props does not contains a `name`
      return (
        <TextField {...props />
      )
    }
```

The `props` object in the `render` prop contains props like `onBlur` and many others, but `name` is not one of them.

Did I miss anything?

**Comment by bluebill1049** [comment]
which version are you using? only 6.4.0 expose name in the props.
