### ISSUE TITLE
Typescript error if FormValues does not contain any nested attributes.

### ISSUE THREAD

**Issue by marklawlor** [react-hook-form/strictly-typed#21]
## Reproduction

[https://codesandbox.io/s/react-hook-form-usetypedcontroller-forked-hdzbr?file=/src/App.tsx]( https://codesandbox.io/s/react-hook-form-usetypedcontroller-forked-hdzbr?file=/src/App.tsx)

This was created by forking the offical example and updating all versions to the latest

## Issue

Line 32 has error

```
 Types of parameters 'name' and 'name' are incompatible.
            Type 'string' is not assignable to type '"uncontrolled" | "controlled" | "error"'.
```

If you uncomment lines `23-26` the example will work as expected.

## Expected behaviour

Nested attributes should not be a requirement when using @hookform/strictly-typed and typescript

**Comment by bluebill1049** [comment]
possible related to this bug: https://github.com/react-hook-form/react-hook-form/issues/3002 introduced in 6.8.5

**Comment by bluebill1049** [comment]
This should be resolved by the latest.
