### ISSUE TITLE
Improve type safety

### ISSUE THREAD

**Issue by farnoy** [react-hook-form/strictly-typed#9]
**Is your feature request related to a problem? Please describe.**
I'd like my forms to be more strongly typed to avoid any mismatch between inputs in the DOM, validations defined by the form and the submit handler.

**Describe the solution you'd like**
I'd like a solution that's careful about how it uses and transforms my types, so I could trust it more as a type safe library, not just a form library with better autocomplete. Here's a concept:

```ts
interface Inputs {
  firstName: string;
  lastName: string;
  middleNames: Array<{middleName: string;}>;
  age: number;
}

const { control, handleSubmit } = useForm<Inputs>({validate: {presence: ['firstName', 'lastName'] as const}});

// UseFormOptions['validate']['presence'] would be 'firstName' | 'lastName'
// InvertInputs<Inputs, 'firstName' | 'lastName'> would be 'middleNames' | 'age'
// MarkPartial<{a: string}, 'a'> would transform it to {a: string | undefined}
function onSubmit(data: MarkPartial<Inputs, InvertInputs<Inputs, UseFormOptions['validate']['presence']>>) {
  type Test1 = typeof data.firstName;
  // string
  type Test2 = typeof data.age;
  // number | undefined
  // note the automatic undefined
}
return <form onSubmit={handleSubmit(onSubmit)}>
  <Controller
    as='input'
    name='firstName' // firstName validated against `keyof Inputs`, this works today
    control={control}
  />
</form>
```

This example shows a safer transformation of types. Right now it's possible to define any types you want and not be sure of anything in onSubmit. The above snippet might not be enough, sometimes it's tricky to have values at the type level and runtime level and keep them aligned, but I hope something like this is possible.

I also propose improving the Field Array functionality by delegating the `control` variable downstream. If it was possible for `useFieldArray` to return it's own `control` object, we could propagate this type safety into nested and repeated fields, which would be excellent.

**Describe alternatives you've considered**
I considered staying with redux-form, but it's even less type friendly.

**Additional context**
I'm liking the library a lot so far, but I want to migrate to something that uses TypeScript to keep my forms in check.

**Comment by bluebill1049** [comment]
in terms of FieldArray, I think we do have plan to introduce `useTypedFieldArray.

**Comment by farnoy** [comment]
OK, I tried it out and it's excellent! By "delegating" I meant to use a divide & conquer approach for nested/repeating types, but that seems completely unnecessary now that `TypedController` handles `DeepPath`, so disregard my earlier comment.

Still, my other point about types not matching validation methods stands, it's possible to define a field like `age: number` and get an `undefined` value in `onSubmit`.

**Comment by bluebill1049** [comment]
> Still, my other point about types not matching validation methods stands, it's possible to define a field like `age: number` and get an `undefined` value in `onSubmit`.

that's possible with Controller and as long as your component support undefined and number as value.

**Comment by farnoy** [comment]
This isn't the best demo, but here goes: https://codesandbox.io/s/react-hook-form-usetypedcontroller-e1bwc?file=/src/App.tsx

It's possible to get the following print out in the console:
```
Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by Controller)
    in Controller (at useTypedController.tsx:28)
    in Unknown (at App.tsx:34)
    in section (at App.tsx:32)
    in form (at App.tsx:31)
    in ThemeProvider (at App.tsx:29)
    in App (at src/index.tsx:7)

Object {age: "ds"}

Object {age: undefined}
```

The warning is some other issue, but if I input `ds` and submit, I arrive in my `onSubmit` with `{age: string}`. When I press submit again, right after, I arrive in my `onSubmit` with `{age: undefined}`. Neither of these matches my `FormValues` type.

**Comment by farnoy** [comment]
Regarding your comment about `Controller`, there's also unsafety there because the `onChange` handler is weakly typed, so the following is allowed, even if `event.target.value` of a `<input type=number />` is a string. https://codesandbox.io/s/react-hook-form-usetypedcontroller-7eprp?file=/src/App.tsx

To use TypedController with `render` prop safely, I think I need to pass `setValue` from the parent form down to the input, bypassing `onChange`.

**Comment by bluebill1049** [comment]
sorry I lied, we don't accept `undefine` at `defaultValue` because that's the check for use to injected with `defaultValues`

**Comment by kotarella1110** [comment]
@farnoy I want Reac tHook Form to be type-safe just like you.

> https://github.com/react-hook-form/strictly-typed/issues/9#issuecomment-658145903

<img width="923" alt="スクリーンショット 2020-07-17 12 30 57" src="https://user-images.githubusercontent.com/12913947/87745656-7a57a500-c829-11ea-962e-25fbb45059da.png">

https://react-hook-form.com/api#Controller

> https://github.com/react-hook-form/strictly-typed/issues/9#issuecomment-658149794

onChange event argument cannot be Type-safe.
Are you any good ideas for Type-safe?

https://github.com/react-hook-form/strictly-typed/blob/d066aba6b83e2df6f9807d44d8020177cdbee9a4/src/types.ts#L169

**Comment by farnoy** [comment]
Thanks for pointing out `defaultValues`, that is good to know!

One option would be to remove `onChange` from `TypedController` and pass something like `setValue` instead, but only limited to that field. This would make it incompatible with the default `<input>`, `<select>` and `<textarea>` variants, but we could add typed variants of these for strings/numbers.

So, putting it together:

```ts
// This could even ship with @hookform/strictly-typed, it's so small
function NumberInput(props) {
  const { value, setValue } = props;
  const onChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    // TypedController passes `setValue={(value: T) => this.props.control.setValue(this.props.name, value)}`
    setValue(parseInt(event.target.value, 10));
  }, [setValue]);
  
  return <input {...props} type="number" onChange={onChange} />
}

function SomeForm({}) {
  const { control, handleSubmit } = useForm<Values>({defaultValues: {age: 20}});
  const onSubmit = handleSubmit(...);
  const TypedController = useTypedController({ control });

  return (
    <form onSubmit={onSubmit}>
        <TypedController
          as={NumberInput}
          name="age"
        />

      ...
    </form>
  );
}
```

**Comment by bluebill1049** [comment]
I think we will close this issue for now, once this repo gets more popular, we will invest more effort on it.
